MODULE caesarCipher 
IMPLICIT NONE
CHARACTER(LEN=26) :: ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ" ! comparison string

CONTAINS

! ENCRYPT SUBROUTINE - modifies variables passed as args 
SUBROUTINE ENCRYPT(ALPHABET)



! DECRYPT SUBROUTINE
SUBROUTINE DECRYPT()



! SOLVE SUBROUTINE
SUBROUTINE SOLVE()
END PROGRAM caesarCipher 